/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'LK_StdPeriph' 
 * Target:  'Linko 07x Project_ac6' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "lks32mc07x.h"



#endif /* RTE_COMPONENTS_H */
